config:
  phrases:
    player:
      use-deny: "{aqua}Your class ({green}{class}) {aqua}cannot use {green}{item}{aqua}."
      break-deny: "{aqua}Your class ({green}{class}{aqua}) cannot break {green}{item}{aqua}."
      place-deny: "{aqua}Your class ({green}{class}{aqua}) cannot place {green}{item}{aqua}."
      wear-deny: "{aqua}Your class ({green}{class}{aqua}) cannot wear {green}{item}{aqua}."
      wear-deny-drop: "{aqua}Your inventory was full, so {green}{item}{aqua} was dropped."
      craft-deny: "{aqua}Your class ({green}{class}{aqua}) cannot craft {green}{item}{aqua}."
      smelt-deny: "{aqua}Your class ({green}{class}{aqua}) cannot smelt {green}{item}{aqua}."
  default-class: Classless
  classes:
    - Classless
  defaults:
    stats:
      strength: 1
      resistance: 0
      vitality: 50
      focus: 5
      