config:
  densities:
    base-hardness-multiplier: 15.0      # The number to multiply a block's hardness by if a density is not set in block_densities.yml
  chat:
    format: "{green}[{symbol}] {sender}: {aqua}{message}"     # The default message format to use, if one is not provided in the channel definition
    range-factor-algorithm: "({distance} / {range}) / 4"      # The default algorithm to use to determine how range affects messages
    range-factor-tolerance: 20.0                              # The smallest range factor value that can affect messages
    material-factor-tolerance: 10.0                           # The smallest material factor value that can affect messages
    obfus-tolerance: 15.0                                     # The smallest obfuscation value (how "mangled" a message is) that can affect messages
    announce-on:
      join: true
      leave: true
      ban: true
      kick: true
      pardon: true
  phrases:
    player:
      use-deny: "{aqua}Your class ({green}{class}) {aqua}cannot use {green}{item}{aqua}."
      break-deny: "{aqua}Your class ({green}{class}{aqua}) cannot break {green}{item}{aqua}."
      place-deny: "{aqua}Your class ({green}{class}{aqua}) cannot place {green}{item}{aqua}."
      wear-deny: "{aqua}Your class ({green}{class}{aqua}) cannot wear {green}{item}{aqua}."
      craft-deny: "{aqua}Your class ({green}{class}{aqua}) cannot craft {green}{item}{aqua}."
      smelt-deny: "{aqua}Your class ({green}{class}{aqua}) cannot smelt {green}{item}{aqua}."
      no-damage: "{aqua}Your blows fail to damage {green}{target}{aqua}."
    chat:
      joined-channel: "{aqua}You have joined {green}[{symbol}] {channel}{aqua}."
      focused-channel: "{aqua}Chat focus has been set on {green}{channel}{aqua}."
      leave-channel: "{aqua}You have left {green}[{symbol}] {channel}{aqua}."
      join-channel-announcement: "{green}{player} {aqua}has joined the channel."
      leave-channel-announcement: "{green}{player} {aqua}has left the channel."
      player-banned-announcement: "{green}{player} {aqua}has banned {green}{target} {aqua}from the channel."
      player-kicked-announcement: "{green}{player} {aqua}has kicked {green}{target} {aqua}from the channel."
      player-pardon-announcement: "{green}{player} {aqua}has pardoned {green}{target} {aqua} from his ban."
  leveling:
    level-cap: 20
    experience-algorithm: "50 * ({level} - 1)"
    skill-points: 1
    starting-level: 1
    starting-skill-points: 2
  default-class: Classless
  classes:
    - Classless
  defaults:
    stats:
      strength: 1
      magic: 0
      armor: 0
      aura: 0
      vitality: 50
      precision: 0
      health:
        name: Health
