config:
  phrases:
    player:
      use-deny: "{aqua}Your class ({green}{class}) {aqua}cannot use {green}{item}{aqua}."
      break-deny: "{aqua}Your class ({green}{class}{aqua}) cannot break {green}{item}{aqua}."
      place-deny: "{aqua}Your class ({green}{class}{aqua}) cannot place {green}{item}{aqua}."
      wear-deny: "{aqua}Your class ({green}{class}{aqua}) cannot wear {green}{item}{aqua}."
      craft-deny: "{aqua}Your class ({green}{class}{aqua}) cannot craft {green}{item}{aqua}."
      smelt-deny: "{aqua}Your class ({green}{class}{aqua}) cannot smelt {green}{item}{aqua}."
      no-damage: "{aqua}Your blows fail to damage {green}{target}{aqua}."
  leveling:
    level-cap: 20
    experience-algorithm: "50 * ({level} - 1)"
    skill-points: 1
    starting-level: 1
    starting-skill-points: 2
  default-class: Classless
  classes:
    - Classless
  defaults:
    stats:
      strength: 1
      magic: 0
      armor: 0
      aura: 0
      vitality: 50
      precision: 0
      health:
        name: Health
